name: Build Windows EXE

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller openpyxl

      - name: Build EXE with PyInstaller
        run: |
          pyinstaller --onefile --noconsole ui/app.py --name illustrator_xml_gui

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: illustrator_xml_gui
          path: dist/illustrator_xml_gui.exe

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/illustrator_xml_gui.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
